function unicycle_export_firmware(ctrl, cfg, out_dir)
%UNICYCLE_EXPORT_FIRMWARE  Export embeddable controller parameters.
%
% Excluded families:
%   hybrid_modern
%     Requires persistent integrator states (int_theta_p, int_theta_r) and
%     explicit reset handling on ESTOP. Exporting only the 2x7 gain matrix
%     without the integrator state-management logic would be incorrect.
%
%   baseline_mpc
%     Requires a runtime QP solve. In this configuration the constrained
%     MPC path is a desktop design tool, not an ESP32-ready controller.
%
% Included families:
%   lqr_current, lqr_dob, robust_hinf_like, paper_split
%   The DOB export includes dob_alpha and requires persistent d_est[2] on
%   the firmware side.

if nargin < 3 || isempty(out_dir)
    out_dir = './firmware_export/';
end
if ~exist(out_dir, 'dir')
    mkdir(out_dir);
end

[A, B, ~, ~] = unicycle_plant(cfg);
[Ad, Bd] = unicycle_discretize(A, B, cfg.dt);
L = ctrl.lqr_current.L;

export_data.generated_by = 'unicycle_export_firmware.m';
export_data.timestamp = datestr(now, 'yyyy-mm-dd HH:MM:SS');
export_data.matlab_version = version;

export_data.physical = struct( ...
    'dt', cfg.dt, ...
    'm_body', cfg.m_body, ...
    'L_body', cfg.L_body, ...
    'I_body', cfg.I_body, ...
    'I_body_r', cfg.I_body_r, ...
    'I_rw', cfg.I_rw, ...
    'g', cfg.g, ...
    'tau_rw_max', cfg.tau_rw_max, ...
    'tau_base_max', cfg.tau_base_max, ...
    'omega_rw_max', cfg.omega_rw_max, ...
    'omega_rw_hard', cfg.omega_rw_hard);

export_data.kalman = struct( ...
    'L', flatten_row_major(L), ...
    'L_rows', size(L, 1), ...
    'L_cols', size(L, 2), ...
    'Ad', flatten_row_major(Ad), ...
    'Ad_rows', size(Ad, 1), ...
    'Ad_cols', size(Ad, 2), ...
    'Bd', flatten_row_major(Bd), ...
    'Bd_rows', size(Bd, 1), ...
    'Bd_cols', size(Bd, 2), ...
    'Q_kf_diag', diag(cfg.Q_kf).', ...
    'R_kf_diag', diag(cfg.R_kf).');

export_data.controllers.lqr_current = struct( ...
    'K', flatten_row_major(ctrl.lqr_current.K), ...
    'K_rows', size(ctrl.lqr_current.K, 1), ...
    'K_cols', size(ctrl.lqr_current.K, 2));

export_data.controllers.lqr_dob = struct( ...
    'K', flatten_row_major(ctrl.lqr_dob.K), ...
    'K_rows', size(ctrl.lqr_dob.K, 1), ...
    'K_cols', size(ctrl.lqr_dob.K, 2), ...
    'dob_alpha', ctrl.lqr_dob.dob_alpha);

export_data.controllers.robust_hinf_like = struct( ...
    'K', flatten_row_major(ctrl.robust_hinf_like.K), ...
    'K_rows', size(ctrl.robust_hinf_like.K, 1), ...
    'K_cols', size(ctrl.robust_hinf_like.K, 2));

export_data.controllers.paper_split = struct( ...
    'K_pitch', flatten_row_major(ctrl.paper_split.K_pitch), ...
    'K_pitch_rows', size(ctrl.paper_split.K_pitch, 1), ...
    'K_pitch_cols', size(ctrl.paper_split.K_pitch, 2), ...
    'K_roll', flatten_row_major(ctrl.paper_split.K_roll), ...
    'K_roll_rows', size(ctrl.paper_split.K_roll, 1), ...
    'K_roll_cols', size(ctrl.paper_split.K_roll, 2));

export_data.safety = struct( ...
    'pitch_crash_deg', rad2deg(cfg.pitch_crash_rad), ...
    'roll_crash_deg', rad2deg(cfg.roll_crash_rad), ...
    'omega_rw_max', cfg.omega_rw_max, ...
    'omega_rw_hard', cfg.omega_rw_hard);

json_file = fullfile(out_dir, 'firmware_params.json');
h_file = fullfile(out_dir, 'firmware_params.h');

write_json_export(json_file, export_data);
write_header_export(h_file, export_data, ctrl, cfg, L, Ad, Bd);

fprintf('[Export] firmware_params.json written to %s\n', out_dir);
fprintf('[Export] firmware_params.h   written to %s\n', out_dir);
fprintf('[Export] Controller families exported: lqr_current, lqr_dob,\n');
fprintf('         robust_hinf_like, paper_split\n');
fprintf('[Export] Note: hybrid_modern (7-state) excluded — requires\n');
fprintf('         integrator state not available from IMU alone.\n');
fprintf('[Export] Note: baseline_mpc excluded — requires QP solver at runtime.\n');
end


function write_json_export(json_file, export_data)
try
    json_text = jsonencode(export_data, 'PrettyPrint', true);
catch
    json_text = jsonencode(export_data);
end

fid = fopen(json_file, 'w');
cleanup_fid = onCleanup(@() fclose(fid)); %#ok<NASGU>
fprintf(fid, '%s', json_text);
end


function write_header_export(h_file, export_data, ctrl, cfg, L, Ad, Bd)
fid = fopen(h_file, 'w');
cleanup_fid = onCleanup(@() fclose(fid)); %#ok<NASGU>

fprintf(fid, '/* Auto-generated by unicycle_export_firmware.m — DO NOT EDIT MANUALLY */\n');
fprintf(fid, '#ifndef FIRMWARE_PARAMS_H\n');
fprintf(fid, '#define FIRMWARE_PARAMS_H\n\n');

fprintf(fid, '#define CTRL_DT           %.6ff\n', cfg.dt);
fprintf(fid, '#define CTRL_TAU_RW_MAX   %.6ff\n', cfg.tau_rw_max);
fprintf(fid, '#define CTRL_TAU_BASE_MAX %.6ff\n', cfg.tau_base_max);
fprintf(fid, '#define CTRL_OMEGA_BUDGET %.6ff\n', cfg.omega_rw_max);
fprintf(fid, '#define CTRL_OMEGA_HARD   %.6ff\n', cfg.omega_rw_hard);
fprintf(fid, '#define CTRL_PITCH_CRASH  %.6ff /* rad */\n', cfg.pitch_crash_rad);
fprintf(fid, '#define CTRL_ROLL_CRASH   %.6ff /* rad */\n', cfg.roll_crash_rad);
fprintf(fid, '#define CTRL_IMU_DELAY_SAMPLES %d\n', cfg.imu_delay_samples);
fprintf(fid, '#define CTRL_DOB_ALPHA    %.6ff\n\n', ctrl.lqr_dob.dob_alpha);

write_matrix_2d(fid, 'K_LQR_CURRENT', ctrl.lqr_current.K, 'LQR Current');
write_matrix_2d(fid, 'K_LQR_DOB', ctrl.lqr_dob.K, 'LQR + DOB');
write_matrix_2d(fid, 'K_ROBUST_HINF_LIKE', ctrl.robust_hinf_like.K, 'Robust H-inf-like');
write_matrix_2d(fid, 'K_PAPER_SPLIT_PITCH', ctrl.paper_split.K_pitch, 'Paper Split pitch');
write_matrix_2d(fid, 'K_PAPER_SPLIT_ROLL', ctrl.paper_split.K_roll, 'Paper Split roll');
write_matrix_2d(fid, 'L_KALMAN', L, 'Kalman observer gain');
write_matrix_2d(fid, 'AD', Ad, 'Discrete Ad');
write_matrix_2d(fid, 'BD', Bd, 'Discrete Bd');

fprintf(fid, '#endif /* FIRMWARE_PARAMS_H */\n');
end


function write_matrix_2d(fid, symbol, M, label)
[rows, cols] = size(M);
fprintf(fid, '/* %s — %dx%d, row-major */\n', label, rows, cols);
fprintf(fid, 'static const float %s[%d][%d] = {\n', symbol, rows, cols);
for r = 1:rows
    fprintf(fid, '    { ');
    for c = 1:cols
        suffix = ', ';
        if c == cols
            suffix = ' ';
        end
        fprintf(fid, '%.9ff%s', M(r, c), suffix);
    end
    if r == rows
        fprintf(fid, '}\n');
    else
        fprintf(fid, '},\n');
    end
end
fprintf(fid, '};\n\n');
end


function flat = flatten_row_major(M)
flat = reshape(M.', 1, []);
end
