/* Auto-generated by unicycle_export_firmware.m — DO NOT EDIT MANUALLY */
#ifndef FIRMWARE_PARAMS_H
#define FIRMWARE_PARAMS_H

#define CTRL_DT           0.005000f
#define CTRL_TAU_RW_MAX   0.250000f
#define CTRL_TAU_BASE_MAX 0.400000f
#define CTRL_OMEGA_BUDGET 800.000000f
#define CTRL_OMEGA_HARD   950.000000f
#define CTRL_PITCH_CRASH  0.610865f /* rad */
#define CTRL_ROLL_CRASH   0.610865f /* rad */
#define CTRL_IMU_DELAY_SAMPLES 2
#define CTRL_DOB_ALPHA    0.145364f

/* LQR Current — 2x5, row-major */
static const float K_LQR_CURRENT[2][5] = {
    { 0.000000000f, -0.000000000f, -75.460495461f, -6.699967906f, -0.030766183f },
    { -27.234694756f, -4.357815343f, 0.000000000f, 0.000000000f, 0.000000000f }
};

/* LQR + DOB — 2x5, row-major */
static const float K_LQR_DOB[2][5] = {
    { 0.000000000f, -0.000000000f, -75.460495461f, -6.699967906f, -0.030766183f },
    { -27.234694756f, -4.357815343f, 0.000000000f, 0.000000000f, 0.000000000f }
};

/* Robust H-inf-like — 2x5, row-major */
static const float K_ROBUST_HINF_LIKE[2][5] = {
    { -0.000000000f, -0.000000000f, -70.593091322f, -6.415976040f, -0.027945293f },
    { -24.649474980f, -6.103781678f, 0.000000000f, 0.000000000f, 0.000000000f }
};

/* Paper Split pitch — 1x2, row-major */
static const float K_PAPER_SPLIT_PITCH[1][2] = {
    { -10.788723341f, -2.927414129f }
};

/* Paper Split roll — 1x3, row-major */
static const float K_PAPER_SPLIT_ROLL[1][3] = {
    { -76.190953000f, -6.730751021f, -0.031482906f }
};

/* Kalman observer gain — 5x5, row-major */
static const float L_KALMAN[5][5] = {
    { 0.130380039f, 0.000000000f, 0.016249460f, 0.000000000f, -0.000000000f },
    { 0.055563157f, 0.000000000f, 0.250270762f, 0.000000000f, -0.000000000f },
    { 0.000000000f, 0.105335296f, -0.000000000f, 0.046157839f, -0.000000000f },
    { 0.000000000f, 0.182033048f, -0.000000000f, 0.341969139f, -0.000000000f },
    { 0.000000000f, 0.000000000f, -0.000000000f, 0.000000000f, 0.011118015f }
};

/* Discrete Ad — 5x5, row-major */
static const float AD[5][5] = {
    { 1.000329268f, 0.005000549f, 0.000000000f, 0.000000000f, 0.000000000f },
    { 0.131714590f, 1.000329268f, 0.000000000f, 0.000000000f, 0.000000000f },
    { 0.000000000f, 0.000000000f, 1.001621813f, 0.005002703f, 0.000000000f },
    { 0.000000000f, 0.000000000f, 0.648900571f, 1.001621813f, 0.000000000f },
    { 0.000000000f, 0.000000000f, 0.000000000f, 0.000000000f, 1.000000000f }
};

/* Discrete Bd — 5x2, row-major */
static const float BD[5][2] = {
    { 0.000000000f, -0.000141028f },
    { 0.000000000f, -0.056414133f },
    { -0.000694632f, 0.000000000f },
    { -0.277927929f, 0.000000000f },
    { 27.548209366f, 0.000000000f }
};

#endif /* FIRMWARE_PARAMS_H */
